import numpy as np
from gym.utils import seeding


np_random, seed = seeding.np_random(24)
print(seed)
print(np_random.uniform())
print(np_random.uniform())
print(np_random.uniform())
print(np_random.uniform())
print(np_random.uniform())
print(np_random.uniform())

np_random, seed = seeding.np_random(24)
print(seed)
print(np_random.uniform())
print(np_random.uniform())
print(np_random.uniform())
print(np.random.uniform())
print(np_random.uniform())
print(np_random.uniform())
print(np_random.uniform())


# np_random, seed = seeding.np_random(24)
# print(seed)
# print(np_random.uniform())
# print(np_random.randint(0, 10))
# print(np_random.uniform())
# print(np_random.uniform())
# print(np_random.uniform())
# print(np_random.uniform())
# np_random, seed = seeding.np_random(24)
# print(seed)
# print(np_random.uniform())
# print(np_random.randint(0, 10))
# print(np_random.randint(0, 10))
# print(np_random.uniform())
# print(np_random.uniform())
# print(np_random.uniform())
# print(np_random.uniform())

# np_random, seed = seeding.np_random(24)
# print(seed)
# print(np_random.randint(0, 10))
# print(np_random.randint(0, 10))
# print(np_random.randint(0, 10))
# print(np_random.randint(0, 10))
# print(np_random.randint(0, 10))
# print(np_random.randint(0, 10))

# np_random, seed = seeding.np_random(24)
# print(seed)
# print(np_random.uniform())
# print(np_random.uniform())
# print(np_random.randint(0, 10))
# print(np_random.randint(0, 10))
# print(np_random.uniform())
# print(np_random.uniform())

# np_random, seed = seeding.np_random(24)
# print(seed)
# print(np_random.uniform())
# print(np_random.uniform())
# print(np_random.uniform())
# print(np_random.uniform())
# print(np_random.randint(0, 10))
# print(np_random.randint(0, 10))
# np_random, seed = seeding.np_random(24)
# print(seed)
# print(np_random.randint(0, 10))
# print(np_random.randint(0, 10))
# print(np_random.uniform())
# print(np_random.uniform())
# print(np_random.uniform())
# print(np_random.uniform())

